Create Billing template
teemops/templates pull request #2
Opened 2020-12-02 02:52 UTC by zavierboyd

2020-12-02 06:59 UTC, kiwifellows commented on cloudformation/newaccount/security.iam.groups.cnf.yaml
> +              - !FindInMap [ RoleARN, production, adminro ]
Replace with - !FindInMap [RoleARN, production, adminfull]

2020-12-02 07:00 UTC, kiwifellows commented on cloudformation/newaccount/security.iam.groups.cnf.yaml
> +              - !FindInMap [ RoleARN, development, adminro ]
Replace with - !FindInMap [ RoleARN, development, adminfull ]

2020-12-02 07:01 UTC, kiwifellows commented on cloudformation/newaccount/security.iam.groups.cnf.yaml
> +              - !FindInMap [ RoleARN, billing, adminro ]
Replace with - !FindInMap [ RoleARN, billing, adminfull ]

2020-12-02 07:02 UTC, kiwifellows requested changes
Good work @zavierboyd just found a few minor things to change and can redo PR

2020-12-02 22:40 UTC, kiwifellows commented on cloudformation/newaccount/security.iam.groups.cnf.yaml
> +      adminro: !Join
Apologies I only just saw this error from running the CFN inside AWS which caused a Mapping error.
lists should be as follows for Mappings (AWS CFN is really inconsistent sometimes with lists)
```yaml
Mappings: 

  # Creation of IAM ARNs for organisation roles
  RoleARN:
    production:
      adminro:
        - !Join
          - ""
          - - "arn:aws:iam::"
            - !Ref IAMProdAccountId
            - ":role/CompanyAdminRO"
```

2020-12-03 22:00 UTC, zavierboyd commented on cloudformation/newaccount/security.iam.groups.cnf.yaml
> +      adminro: !Join
I have changed that out for using !Sub instead. Makes it more readable. I have also created a devcontainer with cfn-lint extension. Will run after each file save and check the cfn template. This will prevent mistakes and fix things.

2020-12-13 23:59 UTC, merged